# Generated by Django 3.0.2 on 2020-01-20 14:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a Product Category...', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='Enter Email for Contact us', max_length=100)),
                ('phone', models.CharField(help_text='Enter phone for Contact us', max_length=100)),
                ('address', models.CharField(help_text='Enter address for Contact us', max_length=100)),
                ('instagram', models.CharField(help_text='Enter instagram link for Contact us', max_length=100)),
                ('facebook', models.CharField(help_text='Enter facebook link for Contact us', max_length=100)),
                ('google', models.CharField(help_text='Enter google link for Contact us', max_length=100)),
                ('twitter', models.CharField(help_text='Enter twitter for Contact us', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Product Name...', max_length=100)),
                ('description', models.TextField(help_text='Enter a description for this product', max_length=1000)),
                ('price', models.CharField(help_text='Enter a PRICE for this product', max_length=100)),
                ('brand', models.CharField(help_text='Enter a BRAND for this product', max_length=100)),
                ('sold_nums', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available')], default='available', max_length=60)),
                ('sex', models.CharField(choices=[('men', 'Men`s'), ('women', 'Women`s'), ('boy', 'Boy`s'), ('girl', 'Girl`s')], default='men', max_length=60)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for particular Product in whole Shop', primary_key=True, serialize=False)),
                ('size', models.CharField(help_text='Enter Size for this product', max_length=50)),
                ('color', models.CharField(help_text='Enter Color for this product', max_length=50)),
                ('num', models.IntegerField(help_text='Enter Avalible Number for this product')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Product')),
            ],
        ),
    ]
