# Generated by Django 3.0.2 on 2020-01-21 08:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='google',
        ),
        migrations.AddField(
            model_name='company',
            name='telegram',
            field=models.CharField(blank=True, help_text='Enter telegram link for Contact us', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, help_text='Enter address for Contact us', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.CharField(blank=True, help_text='Enter Email for Contact us', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='facebook',
            field=models.CharField(blank=True, help_text='Enter facebook link for Contact us', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='instagram',
            field=models.CharField(blank=True, help_text='Enter instagram link for Contact us', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, help_text='Enter phone for Contact us', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='twitter',
            field=models.CharField(blank=True, help_text='Enter twitter for Contact us', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productinstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for particular Product in whole Shop', primary_key=True, serialize=False),
        ),
    ]
