# Generated by Django 3.0.2 on 2020-01-27 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_auto_20200121_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='facebook',
            field=models.CharField(blank=True, default='#', help_text='Enter facebook link for Contact us', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='instagram',
            field=models.CharField(blank=True, default='#', help_text='Enter instagram link for Contact us', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='telegram',
            field=models.CharField(blank=True, default='#', help_text='Enter telegram link for Contact us', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='twitter',
            field=models.CharField(blank=True, default='#', help_text='Enter twitter for Contact us', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(default=1)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.ProductInstance')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('total', models.IntegerField(default=0)),
                ('item_list', models.ManyToManyField(to='shop.CartItem')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
