# Generated by Django 3.0.2 on 2020-01-30 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200127_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['item']},
        ),
    ]
