# Generated by Django 3.0.2 on 2020-02-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200205_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='images',
        ),
        migrations.AddField(
            model_name='company',
            name='images',
            field=models.ManyToManyField(to='shop.Image'),
        ),
    ]
